apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: alain-nguyen
metadata:
  name: tpl-postgresql
  namespace: ${NAMESPACE}
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: postgresql-secret
    namespace: ${NAMESPACE}
  data:
    database-name: ${DATABASE_NAME}
    database-password: ${DATABASE_PASSWORD}
    database-user: ${DATABASE_USER}
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: postgresql-svc
    namespace: ${NAMESPACE}
  spec:
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: postgresql
- apiVersion: v1 
  kind: PersistentVolumeClaim
  metadata:
    name: postgresql-pvc
    namespace: ${NAMESPACE}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
parameters:
- description: Value for namespace
  displayName: Name
  name: NAMESPACE
  required: true
- description: Value for displayname
  displayName: Display Name
  name: NAMESPACE_DISPLAY_NAME
  required: true
- description: Text
  displayName: Description
  name: NAMESPACE_DESCRIPTION
- description: name of database
  displayName: Database Name
  name: DATABASE_NAME
- description: name of user
  displayName: User
  name: DATABASE_USER
- description: password
  displayName: Password
  name: DATABASE_PASSWORD