apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: any
labels:
  template: any
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: postgresql-secret
    namespace: ${NAMESPACE}
  data:
    database-name: ZGItc2Fub2Zp
    database-password: cDQ1NXcwcmQ=
    database-user: dXNlci1zYW5vZmk=
  type: Opaque
parameters:
- description: Name
  displayName: Name
  name: NAMESPACE
  required: true